version: '2'
services:
  mirakurun:
    image: a2ito/mirakurun:latest-amd64
    container_name: mirakurun
    privileged: true
    ports:
      - "40772:40772"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /mnt/Sharedisk:/sharedisk:rw

  chinachu:
    image: a2ito/chinachu:latest-amd64
    container_name: dc-chinachu
    ports:
     - "10772:10772"
     - "20772:20772"
     - "5353:5353/udp"
    volumes:
     - /etc/localtime:/etc/localtime:ro
    links:
     - mirakurun:container-mirakurun
